export const SERVICES_DATA = [
  {
    id: 'trial-makeup',
    title: 'Trial Makeup',
    para:'LIVE UPTO YOUR INSPIRATION',
    description1: 'Is there a special look that you always had in mind for your wedding? Is it the looks of your favorite movie star of the ‘70s or the latest heart-throb? It is time to check out if that glorious look works out for you. Come to Inspirit Makeovers and we will help you recreate that special look in a fabulously modern way – so that your inspiration becomes an expression of beauty on your special day. It is time to check out the ensemble, the designer wear and how your wedding sari would look by trying out a nearly same colour saree and clicking a few photographs. Or maybe you wish to try out a look that you had seen at a wedding of a distant cousin in a major city. Yes, the latest fashion and the trendiest looks are what you are looking for. We give all the glamourous looks you have in mind a modern twist. We make you look ready for your big day with the perfect look – making you feel completely comfortable and confident. You will be completely aware that you look absolutely stunning and everyone is going to ga-ga over your gorgeous looks.',
    description2:'Or maybe you wish to try out a look that you had seen at a wedding of a distant cousin in a major city. Yes, the latest fashion and the trendiest looks are what you are looking for. We give all the glamourous looks you have in mind a modern twist. We make you look ready for your big day with the perfect look – making you feel completely comfortable and confident. You will be completely aware that you look absolutely stunning and everyone is going to ga-ga over your gorgeous looks.',
    image: 'assets/images/IMG_0221.JPG'
  },
  {
    id: 'bridal-makeup',
    title: 'Bridal Makeup & Hair',
    description1: 'Is there a special look that you always had in mind for your wedding? Is it the looks of your favorite movie star of the ‘70s or the latest heart-throb? It is time to check out if that glorious look works out for you. Come to Inspirit Makeovers and we will help you recreate that special look in a fabulously modern way – so that your inspiration becomes an expression of beauty on your special day. It is time to check out the ensemble, the designer wear and how your wedding sari would look by trying out a nearly same colour saree and clicking a few photographs. Or maybe you wish to try out a look that you had seen at a wedding of a distant cousin in a major city. Yes, the latest fashion and the trendiest looks are what you are looking for. We give all the glamourous looks you have in mind a modern twist. We make you look ready for your big day with the perfect look – making you feel completely comfortable and confident. You will be completely aware that you look absolutely stunning and everyone is going to ga-ga over your gorgeous looks.',
    description2:'Or maybe you wish to try out a look that you had seen at a wedding of a distant cousin in a major city. Yes, the latest fashion and the trendiest looks are what you are looking for. We give all the glamourous looks you have in mind a modern twist. We make you look ready for your big day with the perfect look – making you feel completely comfortable and confident. You will be completely aware that you look absolutely stunning and everyone is going to ga-ga over your gorgeous looks.',
    image: 'assets/images/IMG_0220.JPG'
  },
  {
    id: 'family-friends',
    title: 'Family & Friends',
    description1: 'Is there a special look that you always had in mind for your wedding? Is it the looks of your favorite movie star of the ‘70s or the latest heart-throb? It is time to check out if that glorious look works out for you. Come to Inspirit Makeovers and we will help you recreate that special look in a fabulously modern way – so that your inspiration becomes an expression of beauty on your special day. It is time to check out the ensemble, the designer wear and how your wedding sari would look by trying out a nearly same colour saree and clicking a few photographs. Or maybe you wish to try out a look that you had seen at a wedding of a distant cousin in a major city. Yes, the latest fashion and the trendiest looks are what you are looking for. We give all the glamourous looks you have in mind a modern twist. We make you look ready for your big day with the perfect look – making you feel completely comfortable and confident. You will be completely aware that you look absolutely stunning and everyone is going to ga-ga over your gorgeous looks.',
    description2:'Or maybe you wish to try out a look that you had seen at a wedding of a distant cousin in a major city. Yes, the latest fashion and the trendiest looks are what you are looking for. We give all the glamourous looks you have in mind a modern twist. We make you look ready for your big day with the perfect look – making you feel completely comfortable and confident. You will be completely aware that you look absolutely stunning and everyone is going to ga-ga over your gorgeous looks.',
    image: 'assets/images/IMG_0224.JPG'
  },
  {
    id: 'mehandi',
    title: 'Mehandi',
    description1: 'Is there a special look that you always had in mind for your wedding? Is it the looks of your favorite movie star of the ‘70s or the latest heart-throb? It is time to check out if that glorious look works out for you. Come to Inspirit Makeovers and we will help you recreate that special look in a fabulously modern way – so that your inspiration becomes an expression of beauty on your special day. It is time to check out the ensemble, the designer wear and how your wedding sari would look by trying out a nearly same colour saree and clicking a few photographs. Or maybe you wish to try out a look that you had seen at a wedding of a distant cousin in a major city. Yes, the latest fashion and the trendiest looks are what you are looking for. We give all the glamourous looks you have in mind a modern twist. We make you look ready for your big day with the perfect look – making you feel completely comfortable and confident. You will be completely aware that you look absolutely stunning and everyone is going to ga-ga over your gorgeous looks.',
    description2:'Or maybe you wish to try out a look that you had seen at a wedding of a distant cousin in a major city. Yes, the latest fashion and the trendiest looks are what you are looking for. We give all the glamourous looks you have in mind a modern twist. We make you look ready for your big day with the perfect look – making you feel completely comfortable and confident. You will be completely aware that you look absolutely stunning and everyone is going to ga-ga over your gorgeous looks.',
    image: 'assets/images/IMG_0226.JPG'
  }
];
